### ISSUE TITLE
update `requirements-write.txt`

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymc-examples#448]
The current requirements file is out of date and potentially too minimal

https://github.com/pymc-devs/pymc-examples/blob/dce63a03b894d39a0a39a4773f9a0226078391c1/requirements-write.txt#L1-L9

# Todo
- [ ] Replace `pymc3` with `pymc`, possibly with a `>=4.0` version tag.
- [ ] We don't need to have total coverages of _all_ packages used in the repo, but it would be helpful to add more commonly used packages such as: 
  - `matplotlib`
  - `numpy`
  - `xarray`
  - `seaborn`
  - `bambi`
  - `jupyterlab-code-formatter`, `isort` (useful when writing notebooks in the browser, rather than VS Code for example)
  - `patsy`
  - `scipy`
  - `daft` (for making causal DAG's)
- [ ] Check version on `pre-commit` is still appropriate
- [ ] Update instructions in final section of the [contributing guide](https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md) to include the instructions on how to build a `pymc-examples-env` environment. E.g. `conda create --name pymc-examples-env --file requirements-write.txt`

Happy to take feedback on this of course.

**Comment by OriolAbril** [comment]
I agree with most of the points,  but would try to keep the requirements there minimal.

Expanding and being explicit on all downstream dependencies we use explicitly is a good idea I think too. Therefore, numpy, scipy, pandas, xarray, matplotlib, arviz. I would also add graphviz (unless there is an option for pymc[all] or something of the sort that installs pymc and optional dependencies. Regarding the others I think we could add some extra libraries that are not pymc dependencies (direct or indirect) but I would be quite strict on that.
