### ISSUE TITLE
Broken notebooks

### ISSUE THREAD

**Issue by williambdean** [pymc-devs/pymc-examples#723]
Checking for stale notebooks...

groups based on the directory structure in the `examples` folder. For example, casual_inference is `examples/casual_inference` and any notebook in that directory is part of the `casual_inference` group.

<details>
<summary>Workflow</summary>

Using the logic from #740 to run the notebooks either mocked or not.

Example command: `python -m scripts/notebook_runner/runner.py --notebooks examples/casual_inference`

This will print out the errors with are used in the specific issues.

</details>

**NOTE:** These checks are not on the validity of the notebooks, but rather that they run through without any errors.

## casual_inference

<details open><summary>Notebooks</summary>

- bayesian_nonparametric_causal.ipynb
  - [x] checked
  - [ ] runs without error #724
- excess_deaths.ipynb
  - [x] checked
  - [x] runs without error
- regression_discontinuity.ipynb
  - [x] checked
  - [ ] runs without error #725
- moderation_analysis.ipynb
  - [x] checked
  - [x] runs without error
- mediation_analysis.ipynb
  - [x] checked
  - [x] runs without error
- GLM-simpsons-paradox.ipynb
  - [x] checked
  - [x] runs without error
- difference_in_differences.ipynb
  - [x] checked
  - [x] runs without error
- bayesian_ab_testing_introduction.ipynb
  - [x] checked
  - [x] runs without error
- interventional_distribution.ipynb
  - [x] checked
  - [x] runs without error
- interrupted_time_series.ipynb
  - [x] checked
  - [x] runs without error

</details>

## samplers

<details open><summary>Notebooks</summary>

- DEMetropolisZ_tune_drop_fraction.ipynb
  - [x] checked
  - [x] runs without error
- lasso_block_update.ipynb
  - [x] checked
  - [x] runs without error
- DEMetropolisZ_EfficiencyComparison.ipynb
  - [x] checked
  - [ ] runs without error #731
- fast_sampling_with_jax_and_numba.ipynb
  - [x] checked
  - [x] runs without error
- MLDA_variance_reduction_linear_regression.ipynb
  - [x] checked
  - [ ] runs without error #729
- SMC2_gaussians.ipynb
  - [x] checked
  - [x] runs without error
- sampling_conjugate_step.ipynb
  - [x] checked
  - [ ] runs without error #730
- MLDA_introduction.ipynb
  - [x] checked
  - [x] runs without error
- SMC-ABC_Lotka-Volterra_example.ipynb
  - [x] checked
  - [ ] runs without error #732
- sampling_compound_step.ipynb
  - [x] checked
  - [ ] runs without error #728
- MLDA_simple_linear_regression.ipynb
  - [x] checked
  - [ ] runs without error #727
- MLDA_gravity_surveying.ipynb
  - [x] checked
  - [ ] runs without error #726

</details>

## survival_analysis

<details open><summary>Notebooks</summary>

- bayes_param_survival.ipynb
  - [x] checked
  - [x] runs without error
- survival_analysis.ipynb
  - [ ] checked
  - [ ] runs without error
- weibull_aft.ipynb
  - [x] checked
  - [ ] runs without error #746
- censored_data.ipynb
  - [ ] checked
  - [ ] runs without error
- frailty_models.ipynb
  - [ ] checked
  - [ ] runs without error

</details>

## time_series

<details open><summary>Notebooks</summary>

- bayesian_var_model.ipynb
  - [ ] checked
  - [ ] runs without error
- MvGaussianRandomWalk_demo.ipynb
  - [ ] checked
  - [ ] runs without error
- Time_Series_Generative_Graph.ipynb
  - [ ] checked
  - [ ] runs without error
- Air_passengers-Prophet_with_Bayesian_workflow.ipynb
  - [ ] checked
  - [ ] runs without error
- Euler-Maruyama_and_SDEs.ipynb
  - [ ] checked
  - [ ] runs without error
- Forecasting_with_structural_timeseries.ipynb
  - [ ] checked
  - [ ] runs without error
- stochastic_volatility.ipynb
  - [ ] checked
  - [ ] runs without error
- longitudinal_models.ipynb
  - [ ] checked
  - [ ] runs without error
- AR.ipynb
  - [ ] checked
  - [ ] runs without error

</details>

## generalized_linear_models

<details open><summary>Notebooks</summary>

- GLM-discrete-choice_models.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-robust.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-binomial-regression.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-negative-binomial-regression.ipynb
  - [ ] checked
  - [ ] runs without error
- multilevel_modeling.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-out-of-sample-predictions.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-model-selection.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-hierarchical-binomial-model.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-rolling-regression.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-truncated-censored-regression.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-robust-with-outlier-detection.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-ordinal-regression.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-poisson-regression.ipynb
  - [ ] checked
  - [ ] runs without error

</details>

## bart

<details open><summary>Notebooks</summary>

- bart_categorical_hawks.ipynb
  - [ ] checked
  - [ ] runs without error
- bart_quantile_regression.ipynb
  - [ ] checked
  - [ ] runs without error
- bart_heteroscedasticity.ipynb
  - [ ] checked
  - [ ] runs without error
- bart_introduction.ipynb
  - [ ] checked
  - [ ] runs without error

</details>

## introductory

<details open><summary>Notebooks</summary>

- api_quickstart.ipynb
  - [ ] checked
  - [ ] runs without error

</details>

## variational_inference

<details open><summary>Notebooks</summary>

- empirical-approx-overview.ipynb
  - [ ] checked
  - [ ] runs without error
- variational_api_quickstart.ipynb
  - [ ] checked
  - [ ] runs without error
- pathfinder.ipynb
  - [ ] checked
  - [ ] runs without error
- GLM-hierarchical-advi-minibatch.ipynb
  - [ ] checked
  - [ ] runs without error
- bayesian_neural_network_advi.ipynb
  - [ ] checked
  - [ ] runs without error

</details>

## howto

<details open><summary>Notebooks</summary>

- wrapping_jax_function.ipynb
  - [ ] checked
  - [ ] runs without error
- model_builder.ipynb
  - [ ] checked
  - [ ] runs without error
- copula-estimation.ipynb
  - [ ] checked
  - [ ] runs without error
- Missing_Data_Imputation.ipynb
  - [ ] checked
  - [ ] runs without error
- profiling.ipynb
  - [ ] checked
  - [ ] runs without error
- spline.ipynb
  - [ ] checked
  - [ ] runs without error
- updating_priors.ipynb
  - [ ] checked
  - [ ] runs without error
- howto_debugging.ipynb
  - [ ] checked
  - [ ] runs without error
- LKJ.ipynb
  - [ ] checked
  - [ ] runs without error
- marginalizing-models.ipynb
  - [ ] checked
  - [ ] runs without error
- blackbox_external_likelihood_numpy.ipynb
  - [ ] checked
  - [ ] runs without error

</details>

## case_studies

<details open><summary>Notebooks</summary>

- factor_analysis.ipynb
  - [x] checked
  - [x] runs without error
- item_response_nba.ipynb
  - [x] checked
  - [x] runs without error
- CFA_SEM.ipynb
  - [ ] checked
  - [ ] runs without error
- reliability_and_calibrated_prediction.ipynb
  - [x] checked
  - [x] runs without error
- GEV.ipynb
  - [x] checked
  - [x] runs without error
- binning.ipynb
  - [x] checked
  - [ ] runs without error #744
- putting_workflow.ipynb
  - [ ] checked
  - [ ] runs without error
- reinforcement_learning.ipynb
  - [x] checked
  - [x] runs without error
- probabilistic_matrix_factorization.ipynb
  - [x] checked
  - [ ] runs without error #743
- BEST.ipynb
  - [x] checked
  - [x] runs without error
- rugby_analytics.ipynb
  - [x] checked
  - [x] runs without error
- hierarchical_partial_pooling.ipynb
  - [x] checked
  - [x] runs without error

</details>

## gaussian_processes

<details open><summary>Notebooks</summary>

- gaussian_process.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-Latent.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-Heteroskedastic.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-SparseApprox.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-smoothing.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-MaunaLoa.ipynb
  - [ ] checked
  - [ ] runs without error
- log-gaussian-cox-process.ipynb
  - [ ] checked
  - [ ] runs without error
- HSGP-Advanced.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-Births.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-Marginal.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-Kron.ipynb
  - [ ] checked
  - [ ] runs without error
- HSGP-Basic.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-Circular.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-MaunaLoa2.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-MeansAndCovs.ipynb
  - [ ] checked
  - [ ] runs without error
- GP-TProcess.ipynb
  - [ ] checked
  - [ ] runs without error
- MOGP-Coregion-Hadamard.ipynb
  - [ ] checked
  - [ ] runs without error

</details>

## mixture_models

<details open><summary>Notebooks</summary>

- dependent_density_regression.ipynb
  - [x] checked
  - [ ] runs without error #741
- marginalized_gaussian_mixture_model.ipynb
  - [x] checked
  - [ ] runs without error #742
- dp_mix.ipynb
  - [x] checked
  - [x] runs without error
- gaussian_mixture_model.ipynb
  - [x] checked
  - [x] runs without error
- dirichlet_mixture_of_multinomials.ipynb
  - [x] checked
  - [x] runs without error

</details>

## ode_models

<details open><summary>Notebooks</summary>

- ODE_API_shapes_and_benchmarking.ipynb
  - [x] checked
  - [ ] runs without error #736
- ODE_Lotka_Volterra_multiple_ways.ipynb
  - [x] checked
  - [ ] runs without error #739
- ODE_API_introduction.ipynb
  - [x] checked
  - [ ] runs without error #738
- ODE_with_manual_gradients.ipynb
  - [x] checked
  - [ ] runs without error #737

</details>

## spatial

<details open><summary>Notebooks</summary>

- malaria_prevalence.ipynb
  - [x] checked
  - [ ] runs without error #735
- conditional_autoregressive_priors.ipynb
  - [x] checked
  - [x] runs without error
- nyc_bym.ipynb
  - [x] checked
  - [x] runs without error

</details>

## fundamentals

- data_container.ipynb
  - [x] checked
  - [x] runs without error

## diagnostics_and_criticism

<details open><summary>Notebooks</summary>

- Bayes_factor.ipynb
  - [x] checked
  - [x] runs without error
- Diagnosing_biased_Inference_with_Divergences.ipynb
  - [x] checked
  - [ ] runs without error #733
- model_averaging.ipynb
  - [x] checked
  - [ ] runs without error #734
- sampler-stats.ipynb
  - [x] checked
  - [x] runs without error

</details>
